-- ============================================================
-- Thay bộ câu hỏi cũ bằng bộ câu hỏi mới từ file 'Bộ câu hỏi_DNCT.xlsx'
-- (đã rà soát kỹ: bỏ 1 câu trùng y hệt, sửa 2 câu bị trùng với đáp án
-- mâu thuẫn nhau theo đúng lựa chọn bạn đã xác nhận)
-- GIỮ NGUYÊN 22 câu hỏi 5S và đáp án của chúng, không đụng tới.
-- ============================================================

-- Xoá toàn bộ câu hỏi CŨ, trừ các câu thuộc chủ đề '5S'
delete from questions where category is distinct from '5S';

-- Thêm 310 câu hỏi mới từ bộ DNCT (đã làm sạch)
insert into questions (question_text, options, correct_index, category) values
('Lưu lượng bơm nước cấp?', '["25 l/s", "17 l/s", "27 l/s", "22 l/s"]', 2, 'Hệ nước cấp'),
('Liều lượng cồn công nghiệp cho mỗi lần châm vào bồn dinh dưỡng 1000 lít?', '["14 lít", "12 lít", "10 lít", "8 lít"]', 2, 'Hệ thống XLNT'),
('Tỷ lệ NaOH và NaHCO3 khi bổ sung hoá chất?', '["2:1", "1:1", "1:0,5", "0,5:1"]', 3, 'Hệ thống XLNT'),
('Mục đích bổ sung NaHCO3 cho trạm xử lý nước thải là gì?', '["Điều chỉnh PH", "Tăng vi sinh", "Tăng lượng bùn hoạt tính", "Điều chỉnh DO"]', 0, 'Hệ thống XLNT'),
('Hóa chất nào được bổ sung vào tháp khử mùi?', '["NaHCO3", "Axit oxalic", "NaOH", "Cồn công nghiệp"]', 2, 'Hệ thống XLNT'),
('Công dụng của van cân bằng hai bể nước cấp?', '["Cân bằng áp", "Van thông hai bể nước", "Ngăn nước chảy ngược", "Thông hơi"]', 1, 'Hệ nước cấp'),
('Nguyên lý hoạt động cảm biến áp suất nước: 1. Cảm biến, 2. Ngõ ra, 3. Xử Lý, 4. Áp suất', '["1-2-3-4", "3-2-1-4", "4-1-2-3", "4-1-3-2"]', 3, 'Hệ nước cấp'),
('Áp suất làm việc công tắc áp suất Saginomiya SNS-C120', '["0.5-10 Bar", "-0.6 - 10 Bar", "1.0 -12 Bar", "0.8 - 9 Bar"]', 1, 'Hệ nước cấp'),
('Rơ le áp suất đạt điều kiện chạy bơm là bao nhiêu?', '["<2.4kg/Cm2", "<2.6kg/Cm2", "2.8kg/Cm2", "2.7kg/Cm2"]', 0, 'Hệ nước cấp'),
('Biến tần báo lỗi EPH1 là lỗi gì?', '["Lỗi mất 1, 2 hoặc 3 phase đầu ra của biến tần", "Lỗi chạm đất động cơ", "Lỗi mất điện áp đầu vào biến tần", "Lỗi quá dòng động cơ"]', 2, 'Hệ nước cấp'),
('Biến tần báo lỗi 0C1 là lỗi gì?', '["Lỗi chạm đất động cơ", "Lỗi mất 1, 2 hoặc 3 phase đầu ra của biến tần", "Lỗi mất điện áp đầu vào biến tần", "Lỗi quá dòng động cơ"]', 3, 'Hệ nước cấp'),
('Biến tần báo lỗi EPH0 là lỗi gì?', '["Lỗi mất điện áp đầu vào biến tần", "Lỗi quá dòng động cơ", "Lỗi chạm đất động cơ", "Lỗi mất 1, 2 hoặc 3 phase đầu ra của biến tần"]', 3, 'Hệ nước cấp'),
('Dung tích bình tích áp tại trạm bơm cấp?', '["1000 lít", "1500 lít", "2000 lít", "3000 lít"]', 2, 'Hệ nước cấp'),
('Nguồn chính của bơm nước cấp trong bộ ATS được set theo nhánh hạ thế nào ?', '["NMB-UC-01", "NMB-UC-02", "NMB-UC-03", "NMB-PTB-01"]', 2, 'Hệ nước cấp'),
('Van được sử dụng để lọc rác và cặn bã trên hệ thống đường ống; qua đó giúp lưu chất trên đường ống trở nên sạch sẽ hơn là loại nào?', '["Y lọc", "Van xả khí", "Van điều áp", "Van cân bằng"]', 0, 'Hệ nước cấp'),
('Test kit dùng để kiểm tra hàm lượng NO3 trong xử lý nước thải của nhà ga là loại nào?', '["Test NH4/NH3 Sera", "Test NO3 Sera", "Hóa chất AQUACLEAN ACF32", "Hóa chất Aquaclean NA"]', 1, 'Hệ thống XLNT'),
('Muối tái sinh để hoàn nguyên vật liệu lọc ở đâu?', '["Bơm lọc", "Housing lọc tinh", "Lọc xác khuẩn", "Cột lọc MF và AC"]', 3, 'Hệ thống RO'),
('Hóa chất nào được sử dụng để khử khuẩn RO định kỳ?', '["Javel", "Muối tái sinh", "Chất khử khuẩn", "Cồn công nghiệp"]', 2, 'Hệ thống RO'),
('Điều kiện áp suất để gửi cảnh báo sự cố vỡ ống nước gửi cảnh báo về hệ thống SCADA là khi nào ?', '["< 0.5kg/cm^2 duy trì trong 10s", "0.3kg/cm^2 duy trì trong 10s", "0.5kg/cm^2 duy trì trong 12s", "< 0.3kg/cm^2 duy trì trong 12s"]', 3, 'Hệ nước cấp'),
('Cột áp của bơm cấp nước sạch là bao nhiêu?', '["30 mH2O", "35mH2O", "40mH2O", "45mH2O"]', 3, 'Hệ nước cấp'),
('Javel 10% được sử dụng cho công tác định kỳ nào?', '["Khử khuẩn RO", "Vệ sinh bể màng MBR", "Châm vào tháp khử mùi", "Vệ sinh vật liệu lọc RO"]', 1, 'Hệ thống XLNT'),
('Chỉ hoạt động trong các trường hợp bảo trì, bảo dưỡng, test thử bơm trong thời gian ngắn. Hoặc trong các trường hợp đặc biệt khác mà cấp trên cho phép là chế độ chạy nào?', '["Chế độ Auto", "Chế độ MAN", "Chế độ OFF", "Cả 3 đáp án trên đều đúng."]', 1, 'Hệ nước cấp'),
('Nước cấp của nhà ga được cung cấp bởi nguồn từ hệ thống nước sạch được đưa về bể chứa có dung tích bao nhiêu ?', '["1000 m^3", "1500m^3", "2000m^3", "2500m^3"]', 1, 'Hệ nước cấp'),
('Hệ thống mương thoát nước, kanivo  nhà ga dùng để làm gì ?', '["Tưới cây", "Chứa nước", "Nuôi cá", "Chống ngập và bảo vệ thiết bị xung quanh nhà ga"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Hệ thống các hố IC bao quanh nhà ga dùng để làm gì ?', '["Chứa rác", "Kéo dây điện", "Kéo cáp ngầm", "Hố gom nước và hố trung gian do đường ống dài"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Các ống thoát nước mưa trên mái dùng loại ống gì ?', '["Ống kẽm", "Ống đồng", "Ống PPR", "HDPE"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Các nắp thoát sàn trên mái dùng công nghệ gì ?', '["Nano", "RO", "MBR", "SIPHONIC"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Quy định an toàn lao động khi leo lên mái để kiểm tra , vệ sinh các mương thoát nước trên mái ?', '["Đội mũ bảo hộ, đeo đây đai an toàn", "Giày chống trơn trượt", "Áo phản quang", "Cả A, B, C đều đúng"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Có bao nhiêu vị trí leo lên mái lỗ thăm để kiểm tra cần mở khóa ? ( Khu Cip1,2 )', '["1", "3", "4", "2"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Khi nắp thoát sàn bị nghẹt rác thì thông nghẹt vị trí đó như thế nào ?', '["Có hai người kiểm tra và hỗ trợ", "Mang dây đai và súng thông nghẹt", "Vệ sinh rác xung quanh thoát sàn", "Cả A, B, C đều đúng"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Nếu trời mưa to , sấm sét , trơn trượt thì có được leo lên mái kiểm tra không ?', '["Cho phép", "Hết mưa leo lên", "Công việc gấp", "Không cho phép"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Quy định khi leo lên mái để kiểm tra , vệ sinh các mương thoát nước trên mái gồm mấy người ?', '["1", "2", "3", "Cả B, C đều đúng"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Trường hợp máng xối hư hỏng , thoát sàn nghẹt nặng , mái che bị rỉ rét , lủng mái thì cần phối hợp hay báo cho ai để xử lý ?', '["Hottline PKT", "Bảo trì", "Đội ĐNCT", "Cả A, B, C đều đúng"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Quy định kiểm tra định kỳ vệ sinh trên mái do nhà thầu vệ sinh mấy tháng/ 1 lần ?', '["2", "3", "4", "1"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Mương thoát nước nhà ga , nắp gang thoát nước nếu bị ngập tràn lên sàn đi bộ thì xử lý như thế nào ?', '["Tát nước", "Mở nắp cho xả tràn", "Thông nghẹt rác xung quanh lưới chắn rác", "Cả A, B, C đều đúng"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Mương thoát nước nhà ga, nắp gang thoát nước nếu bị ngập tràn vào hố trung thế, hạ thế, phòng máy biến áp thì xử lý như thế nào ?', '["Bơm nước phòng MBA", "Bơm nước phòng HT", "Bơm nước phòng LT", "Cả A, B, C đều đúng"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Nếu mùa mưa bão sắp đến thì cần kiểm tra các mương thoát nước, nắp hố gang như thế nào ?', '["1 năm /1 lần", "1 tháng /1 lần", "1 tuần/ 1 lần", "1 ngày/ 1 lần"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Mương thoát nước ngoài sân đổ, nắp gang thoát nước công dụng nó như thế nào ?', '["Chứa rác", "Trồng cây ăn trái", "Chứa nước", "Chống ngập và thoát nước cho nhà ga"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Hệ thống thoát nước mưa trên mái và thoát nước ngoài nhà, sân đổ thì sẽ chảy đi đâu ?', '["Cống thoát thành phố", "Cống thoát T1", "Bể chứa nước T2", "Bể điều hòa giữ nước sau tòa nhà cảng hàng không quốc tế"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Nếu vào mùa mưa bão thì công tác kiểm tra hệ thống thoát nước mưa, vệ sinh trên mái , vệ sinh các kanivo, các mương thoát nước cần kiểm tra như thế nào?', '["1 tháng/1 lần", "1 tuần/1 lần", "1 năm/1 lần", "1 ngày/1 lần"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Hệ thống thoát nước mưa trên mái cao phía trục J-K/ 10-28 có bao nhiêu vị trí đường ống thoát xuống kanivo ?', '["8", "9", "10", "11"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Hệ thống thoát nước hiện nay tại nhà ga có đảm bảo để bảo vệ an toàn cho người và thiết bị hệ thống', '["Bình thường", "Không an toàn", "Sự cố", "An toàn"]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Xử lý sự cố thoát nước mưa từ trên mái không kịp chảy ra kanivo , mà chảy ra sàn nhà ga , chảy vào mương trung thế, mương LT, phòng máy biến áp.....', '["2 người", "3 người", "4 người", "Tất cả nhân viên vận hành, bảo trì....."]', 3, 'Hệ thoát nước mái nhà ga và mương thoát nước'),
('Hiện tại hệ thống XLNT đang sử dụng bao nhiêu bơm hóa chất ?', '["1", "2", "3", "4"]', 2, 'Hệ thống XLNT'),
('Bơm hóa chất số 1 dùng để bơm hóa chất ở bồn nào ?', '["NaOH", "HaHCO3", "Cả A và B", "Javel"]', 2, 'Hệ thống XLNT'),
('Bơm hóa chất số 3 dùng để bơm hóa chất ở bồn nào?', '["Bơm dinh dưỡng", "Bơm NaOH", "Bơm NaHCO3", "Bơm hóa chất tháp khử mùi"]', 0, 'Hệ thống XLNT'),
('Bơm hóa chất số 5 dùng để bơm hóa chất ở bồn nào?', '["Bơm dinh dưỡng", "Bơm NaOH", "Bơm NaHCO3", "Bơm hóa chất tháp khử mùi"]', 3, 'Hệ thống XLNT'),
('Bơm Liftpit hoạt động dựa trên tín hiệu gì?', '["Phao cao", "Phao thấp", "Tín hiệu điều khiển từ IBMs", "A và B"]', 3, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Nguồn động lực tủ bơm Liftpit được cấp như thế nào ?', '["1 nguồn từ PTB03", "1 Nguồn từ PTB 04", "2 Nguồn độc lập từ PTB03 và PTB04 cho 2 bơm"]', 2, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('2 bơm Liftpit hoạt động tự động theo thời gian như thế nào?', '["Hoạt động xen kẻ theo ngày chẵn và lẻ", "Chạy đồng thời cả 2 bơm", "hoạt động xen kẻ theo relay chuyển (Latching relay)"]', 2, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Tác dụng của Latching relay là gì ?', '["Dùng để chạy bơm luân phiên kết hợp với tín hiệu phao", "Dùng để ngắt bơm khi có sự cố", "Cả 2 đáp án trên"]', 0, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Bơm Liftpit được bảo vệ quá nhiệt như thế nào?', '["Được bảo vệ bởi relay nhiệt lắp đặt trong tủ điều khiển", "Được bảo vệ thông qua  sensor nhiệt có sẵn trong bơm", "Không có bảo vệ quá nhiệt", "Cả A và B"]', 3, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Trong hệ thống XLNT bể điều hòa sử dụng bao nhiêu bơm ?', '["2 bơm 2 cụm", "1 bơm 1 cụm", "4 bơm chia làm 2 cụm", "3 bơm riêng lẻ"]', 2, 'Hệ thống XLNT'),
('Bơm điều hòa hoạt động thông qua biến tần đúng không ?', '["Đúng", "Sai"]', 0, 'Hệ thống XLNT'),
('Tác dụng của bơm điều hòa trong XLNT ?', '["Điều hòa lưu lượng nước phù hợp khi kết hợp cùng tín hiệu phao để bơm nước thải lên bể thiếu khí cho công đoạn xử lí tiếp theo", "Điều hòa lưu lượng nước phù hợp khi kết hợp cùng tín hiệu phao để bơm nước thải lên bể màng MBR cho công đoạn xử lí tiếp theo", "Để bơm nước ra ngoài khi bể điều hòa bị đầy", "Cả A và C"]', 0, 'Hệ thống XLNT'),
('Tác dụng của đèn sự cố ?', '["Duy trì chiếu sáng trong các phòng chức năng khi có sự cố xẩy ra gây mất nguồn điện chiếu sáng", "Dùng để bật tắt chiếu sáng như đèn thông thường", "Dùng để chỉ dẫn lối thoát hiểm"]', 0, 'Hệ thống chiếu sáng'),
('Hệ thống đèn chỉ dẫn thoát hiểm Exit được sử dụng nguồn gì ?', '["Nguồn Pin", "Nguồn thường", "nguồn thường và nguồn pin", "Nguồn U và nguồn Pin"]', 3, 'Hệ thống chiếu sáng'),
('Hệ thống đèn chiếu sáng thang thoát hiểm hoạt động như thế nào ?', '["Hoạt động khi bật công tắc", "Điều khiển từ xa", "Chỉ sáng khi có sự cố", "Hoạt động theo cảm biến radar phát hiện chuyển động để bật tắt đèn"]', 3, 'Hệ thống chiếu sáng'),
('4 bơm điều hòa hiện tại được trang bị tính năng bảo vệ như thế nào ?', '["Bảo vệ quá nhiệt qua Relay nhiệt", "Các tính năng bảo vệ sẵn có trên biến tần hiện hữu đang sử dụng cho bơm (Quá dòng,quá nhiệt...)", "Cả A và B"]', 1, 'Hệ thống XLNT'),
('Trong hệ thống XLNT bơm hóa chất số 3 dùng để bơm chất dinh dưỡng cung cấp cho hệ thống XLNT, vậy chất dinh dưỡng ở đây là gì ?', '["Javel", "NaHCO3", "Cồn công nghiệp (Methanol)"]', 2, 'Hệ thống XLNT'),
('Tác dụng của chất dinh dưỡng methanol trong XLNT ?', '["Rửa màng", "Khử mùi hôi", "Nguồn Carbon hữu cơ để khử Nitơ trong quá trình khử Nitrate thành Nitơ tự do vầ là nguồn dinh dưỡng nuôi cấy vi sinh.", "Cả 3 đáp án trên"]', 2, 'Hệ thống XLNT'),
('Khi 1 bồn cầu bị tắc, sử dụng dụng cụ thông tắc', '["Lò xo", "Súng bắn áp lực", "Bột thông tắc", "Cây lau sàn"]', 1, 'Thiết bị vệ sinh'),
('Xiphong để thay thế cho chậu lavabo phòng khuyết tật', '["TVLF 403", "TVLF 404", "TVLF 405", "Cả 3 đáp án trên đều sai"]', 2, 'Thiết bị vệ sinh'),
('Nguyên nhân pin vòi lavabo cảm biến nhanh hết', '["Van điện từ hỏng", "Mắt cảm biến bị lỗi", "Khách sử dụng nhiều", "Áp lực nước mạnh"]', 1, 'Thiết bị vệ sinh'),
('Khi chậu lavabo bị tắc, cách thông tắc đúng nhất', '["Tháo xiphong rồi dùng súng áp lực bắn đoạn ống thoát trong tường", "Sử dụng bột thông tắc bỏ vô trong xiphong", "Sử dụng súng bắn áp lực bắn ở vị trí nút nhấn xuống", "Cả 3 đáp án trên đều đúng"]', 0, 'Thiết bị vệ sinh'),
('Xiphong để thay thế cho chậu lavabo WC nam(nữ)', '["TVLF 403", "TVLF 404", "TVLF 405", "Cả  A và B đều đúng"]', 0, 'Thiết bị vệ sinh'),
('Loại pin sử dụng cho vòi lavabo', '["2AA", "3AAA", "CR-P2", "CR-P5"]', 2, 'Thiết bị vệ sinh'),
('Nguyên nhân vòi lavabo nước yếu', '["Lưới lọc trước van điện từ bẩn", "Van điện từ hỏng", "Đường ống cấp bị tắc", "Cả  A và C đúng"]', 3, 'Thiết bị vệ sinh'),
('Nguyên nhân vòi lavabo nước chảy liên tục', '["Van điện từ bị hỏng", "Hết pin khi van điện từ chưa kịp đóng", "Mắt cảm biến bị chập chờn", "Cả A và B đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Nguyên nhân vòi xà phòng không lên xà phòng', '["Ống hút bị nứt,bị rơi", "Lò xo bên trong vòi bị gãy", "Hết xà phòng", "Cả 3 đáp án trên đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Loại pin sử dụng cho tiểu nam', '["CR-P2", "2AA", "3AA", "CR-P5"]', 1, 'Thiết bị vệ sinh'),
('Nhà ga có tất cả bao nhiều WC( tính lun khu Cip)', '["23", "24", "25", "26"]', 2, 'Thiết bị vệ sinh'),
('Khi dãy bồn cầu WC nam (nữ) bị tắc, vị trí ống thoát khó thì sử dụng dụng cụ nào để xử lý nhanh nhất', '["Súng bắn áp lực", "Lò xo", "Bột thông tắc", "Cả A,B,C đều sai"]', 1, 'Thiết bị vệ sinh'),
('Nguyên nhân bồn cầu bị rỉ nước xuống sàn', '["Roăn su bị hở", "Ống cấp nước bị hở", "Van phao trong két nước bị hỏng", "Cả A,B,C đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Khi tiểu nam bị tắc, sử  dụng dụng cụ nào để xử lý nhanh nhất', '["Bột thông tắc", "Lò xo", "Súng bắn áp lực", "Cả A,B,C đều đúng"]', 2, 'Thiết bị vệ sinh'),
('Tiểu nam không có nước xả (pin vẫn còn)', '["Hỏng mắt cảm biến", "Hỏng board điều khiểu", "Hỏng van điện từ", "Cả A,B,C đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Nguyên nhân bồn cầu nước chảy liên tục', '["Bộ nhấn xả,bộ điều chỉnh bị hỏng", "Van phao bị kẹt rác", "Lưu lượng nước cấp chảy vô két nước quá yếu", "Cả A,B,C đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Bồn tiểu nước chảy liên tục nguyên nhân do', '["Van điện từ hỏng", "Board điều khiển", "Mắt cảm biến", "Câu B,C đúng"]', 0, 'Thiết bị vệ sinh'),
('Khu WC nào đang sử dụng nguồn điện lưới thay thế cho nguồn pin', '["(1-2)/AB-2F và 11/HJ-GF", "(36-37)/AB-2F và 12/HJ-GF", "(36-37)/AB-2F và 11/HJ-GF", "(1-2)/AB-2F và 12/HJ-GF"]', 1, 'Thiết bị vệ sinh'),
('Công suất định mức theo thiết kế của UPS-LTG?', '["110kVA", "120kVA", "160kVA", "200kVA"]', 1, 'Hệ UPS'),
('Chức năng chính của hệ thống UPS', '["Cung cấp nguồn DC liên tục và ổn định", "Cung cấp nguồn AC liên tục và ổn định", "Cả 2 đáp án đều đúng", "Cả 2 đáp án đều sai"]', 1, 'Hệ UPS'),
('UPS đang hoạt động tại nhà ga có Model là gì', '["Socomec Masterys BC", "Socomec Delphys BC", "Socomec Delphys GP", "Socomec Masterys GP"]', 1, 'Hệ UPS'),
('Công suất định mức theo thiết kế của UPS-EQPT', '["130KVA", "140KVA", "150KVA", "160KVA"]', 3, 'Hệ UPS'),
('Khối chức năng có nhiệm vụ chuyển đổi nguồn điện AC sang DC trong UPS là gì', '["Rectifier", "Inverter", "Battery charger", "Automatic Bypass"]', 0, 'Hệ UPS'),
('Khối chức năng có nhiệm vụ chuyển đổi nguồn điện DC sang AC trong UPS là gì', '["Rectifier", "Inverter", "Battery charger", "Automatic Bypass"]', 1, 'Hệ UPS'),
('Hệ thống ắc quy UPS có nhiệm vụ gì', '["Tự động cấp nguồn cho tải trong trường hợp mất điện lưới đầu vào", "Tự động cấp nguồn cho tải trong trường hợp khối Rectifier lỗi", "A, B đều đúng", "A, B đều sai"]', 2, 'Hệ UPS'),
('Theo quy trình vận hành, đóng switch Q1 để làm gì', '["Cấp nguồn điện lưới đầu vào cho khối Rectier", "Cấp nguồn điện lưới đầu vào cho khối inverter", "Cấp nguồn điện lưới đầu vào cho khối ắc quy", "Cấp nguồn điện lưới đầu vào cho  bypass nội"]', 0, 'Hệ UPS'),
('Theo quy trình vận hành, đóng switch Q2 dùng để làm gì', '["Cấp nguồn điện lưới đầu vào cho khối Rectier", "Cấp nguồn điện lưới đầu vào cho khối inverter", "Cấp nguồn điện lưới đầu vào cho khối ắc quy", "Tất cả đều sai"]', 3, 'Hệ UPS'),
('Theo quy trình vận hành, đóng switch Q3 dùng để làm gì', '["Cấp nguồn điện lưới đầu vào cho khối Rectier", "Cấp nguồn điện lưới đầu vào cho khối inverter", "Cấp nguồn điện lưới đầu vào cho khối ắc quy", "Cấp nguồn đầu ra cho tải"]', 3, 'Hệ UPS'),
('Theo quy trình vận hành, đóng switch Q4 dùng để làm gì', '["Cấp nguồn điện lưới đầu vào cho khối Rectier", "Cấp nguồn điện lưới đầu vào cho khối inverter", "Cấp nguồn điện lưới đầu vào cho khối ắc quy", "Cấp nguồn điện lưới đầu vào cho  bypass nội"]', 3, 'Hệ UPS'),
('Theo quy trình vận hành, đóng switch Q5 dùng để làm gì', '["Cấp nguồn điện lưới đầu vào cho khối Rectier", "Cấp nguồn điện lưới đầu vào cho khối inverter", "Cấp nguồn điện lưới đầu vào cho khối ắc quy", "Cấp nguồn điện lưới đầu vào cho  bypass ngoại"]', 3, 'Hệ UPS'),
('Căn cứ theo tải thực tế hiện tại, thời gian backup của ắc quy khi hoạt động ở chế độ Slow Discharge đối với UPS LTG là bao nhiêu phút', '["110", "111", "112", "113"]', 2, 'Hệ UPS'),
('Căn cứ theo tải thực tế hiện tại, thời gian backup của ắc quy khi hoạt động ở chế độ Slow Discharge đối với UPS EQPT là bao nhiêu phút', '["150", "151", "152", "153"]', 1, 'Hệ UPS'),
('Model ắc quy đang sử dụng cho hệ thống UPS của nhà ga', '["Fiamm 12FLB200P", "Fiamm 12FLB300P", "Fiamm 12FLB400P", "Fiamm 12FLB500P"]', 2, 'Hệ UPS'),
('UPS LTG có tổng cộng bao nhiêu bình ắc quy', '["60", "70", "80", "90"]', 2, 'Hệ UPS'),
('UPS EQPT có tổng cộng bao nhiêu bình ắc quy', '["108", "118", "128", "138"]', 0, 'Hệ UPS'),
('Tiêu chuẩn nội trở đối với chủng loại ắc quy đang sử dụng tại nhà ga (thực hiện phép đo với đồng hồ Hioki BT3554)', '["2.4", "2.5", "2.6", "2.7"]', 0, 'Hệ UPS'),
('Khi UPS hoạt động ở chế độ bình thường (INVERTER MODE), trạng thái ON/OFF các switch như thế nào', '["Trạng thái ON: Q1, Q2, Q3\nTrạng thái OFF: Q4, Q5, Q20", "Trạng thái ON: Q1, Q20, Q3\nTrạng thái OFF: Q4, Q5", "Trạng thái ON: Q1, Q3,Q4, Q20\nTrạng thái OFF: Q5", "Trạng thái ON: Q1, Q20, Q3\nTrạng thái OFF: Q4, Q5"]', 2, 'Hệ UPS'),
('Khi UPS hoạt động ở chế độ bảo dưỡng (MAINTENANCE MODE), trạng thái ON/OFF các switch như thế nào', '["Trạng thái ON: Q1, Q2, Q3\nTrạng thái OFF: Q4, Q5, Q20", "Trạng thái ON: Q1, Q3\nTrạng thái OFF: Q4, Q5, Q20", "Trạng thái ON: Q5, Q20\nTrạng thái OFF: Q1, Q3, Q4", "Trạng thái ON: Q5\nTrạng thái OFF: Q1, Q3, Q4, Q20"]', 3, 'Hệ UPS'),
('Dây mềm nối vào TBVS rắc nối phi bao nhiêu', '["21", "25", "27", "16"]', 0, 'Thiết bị vệ sinh'),
('Dây mềm nối vào vòi lavabo rắc nối phi bao nhiêu', '["21", "25", "27", "16"]', 3, 'Thiết bị vệ sinh'),
('Để nối 2 ống mềm ta dùng gì', '["Dùng keo", "Dùng máy hàn", "Dùng nối 2 đầu ren ngoài", "Phương pháp khác"]', 2, 'Thiết bị vệ sinh'),
('Bồn cầu nước vào yếu do đâu', '["Van mở chưa hết", "Gấp ống dây mềm", "Tắc ống cấp", "Tất cả đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Bồn cầu không xả được nước do đâu', '["Gãy đũa nút nhấn", "Vỡ mặt nạ", "Không có nước vào balo", "Tất cả đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Lavabo rỷ nước do đâu', '["Vỡ roang kết nối", "Kết nối ống thoát chân tường không kín", "Ống xiphong bị lỗ mọt", "Tất cả đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Cách xử lý thoát sàn không thoát', '["Dùng súng hơi áp lực", "Thông đường ống chính", "Thông đường ống từ IC vào", "Tất cả đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Tiểu nam rỷ nước do đâu', '["Roang kết nối bị hở", "Nước rò từ van cấp chảy xuống", "Nứt vỡ ống thoát", "Tất cả đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Nước rỷ chân tường nvs do đâu', '["Nước chảy từ tbvs", "Nước tràn từ mặt đá xuống", "Xilicon dán bàn đá và tường bị hở", "Tất cả đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Máy sấy tay không hoạt động', '["Mất nguồn", "Off công tắc", "Máy hỏng", "Tất cả đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Hộp giấy trên lavabo gắn lên tường bằng gì', '["Keo", "Đinh vít", "Móc", "Giá đỡ"]', 0, 'Thiết bị vệ sinh'),
('Hộp giấy trên bồn cầu gắn lên vách bằng gì', '["Keo", "Đinh vít", "Móc", "Giá đỡ"]', 1, 'Thiết bị vệ sinh'),
('Mùi hôi WC do đâu', '["Quạt hút không đủ", "Bẫy nước thoát sàn trống,", "Vệ sinh chưa tốt", "Tất cả đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Bồn cầu đang sử dụng là loại gì', '["Treo tường", "Gắn sàn", "Loại khác", "Tất cả đều sai"]', 0, 'Thiết bị vệ sinh'),
('Bồn cầu rút nước chậm do', '["Đầy hố IC", "Thông hơi chưa đủ", "Tắc trên đường ống", "Tất cả đều đúng"]', 3, 'Thiết bị vệ sinh'),
('Vòi nước WC tàn tật là loại nào', '["Vòi tự động", "Vòi gạt tay", "Loại khác", "Tất cả đều sai"]', 1, 'Thiết bị vệ sinh'),
('Cây nước A. O. Smith AR600-C-S-1  có bao nhiêu lõi lọc', '["3", "4", "5", "6"]', 1, 'Hệ thống RO'),
('Công suất của cây nước A. O. Smith AR600-C-S-1', '["94L/H", "80L/H", "85L/H", "70L/H"]', 0, 'Hệ thống RO'),
('Tác dụng của lõi lọc  RO Side Stream trong cây nước A. O. Smith AR600-C-S-1', '["Khử mùi và cân bằng vị", "Loại bỏ kim loại vật thể rắn  các thành phần có kích thước lớn", "Loại bỏ các hữu cơ thành phần phụ sau khi khử trùng và các chẩt như Clo", "Loại bỏ các vi khuẩn và vi rút ,kim loại nặng , dư lượng thuốc trừ sâu và các thành phần nguy hại khác"]', 3, 'Hệ thống RO'),
('Nguyên nhân  Cây nước A. O. Smith AR600-C-S-1 bơm hoạt động bình thường nhưng không có nước tinh khiết chảy', '["Lõi lọc thô bị tắc nghẽn", "Bơm bị mất áp hoặc aair khí", "Van cấp1 chiều nước vào  bị hỏng", "Cả 3 phương án trên"]', 3, 'Hệ thống RO'),
('Biện pháp thông nghẹt các cây nước RO ở các  Gate', '["Dùng súng cao áp", "Tháo bộ thu nước thải  vệ sinh", "Dùng máy xịt nước áp xuất cao", "Cả 3 phương án trên"]', 3, 'Hệ thống RO'),
('Nguyên nhân gây ra xì các vòi nước uống', '["Hỏng lớp cao su chặn lõi van", "Lò xo ti van bị mất đàn hồi", "Kẹt nút nhấn van uống nước bằng miệng", "A và B"]', 3, 'Hệ thống RO'),
('Ngoài vị trí cấp cho các cây RO thì nước cấp RO còn cấp những vị trí nào?', '["4 điểm cấp  nước cho tàu bay", "Máy làm nước đá C1", "Chậu rữa bếp C1", "A và B"]', 3, 'Hệ thống RO'),
('Tác dụng của bơm tuần hoàn nước trong hệ thống XLNT', '["Dùng luân  chuyển nước từ để bể   màng qua bể thiếu khí", "Tạo dòng bổ sung oxi  cho bể màn MBR", "Cả A và B", "Bơm nước thải ra  ngoài"]', 2, 'Hệ thống XLNT'),
('Bốn bơm tuần hoàn nước hoạt động như thế nào ?', '["Chạy luân phiên  theo thời gian cài đặc", "Chạy theo từng cặp", "Chạy theo cho độ Man", "Cả 3 phương án trên"]', 0, 'Hệ thống XLNT'),
('4 bơm tuần hoàn nước được bảo vệ như thế nào ?', '["Bảo vệ quá nhiệt qua Relay nhiệt", "Các tính năng bảo vệ sẵn có trên biến tần hiện hữu đang sử dụng cho bơm (Quá dòng,quá nhiệt...)", "Cả A và B"]', 1, 'Hệ thống XLNT'),
('Dòng định mức của bơm tuần hoàn nước XLNT là  bao nhiêu', '["3,7A", "5,4 A", "5A", "10A"]', 0, 'Hệ thống XLNT'),
('Các bơm tuần hoàn nước có báo tín hiệu chạy hoặc sự cố về Scada không', '["Có", "Không"]', 0, 'Hệ thống XLNT'),
('Số lượng bơm tuần hoàn nước bao nhiêu cái', '["2", "4", "6", "8"]', 1, 'Hệ thống XLNT'),
('Bơm tuần hoàn bùn XLNT có công dụng gì ?', '["Các bơm tuần hoàn bùn được sử dụng để thu thập và di chuyển bùn này từ các bể xử lý đến hệ thống MBR", "Bơm tuần hoàn bùn đảm bảo đẩy lượng bùn qua các màn lọc MBR mà không gây tắc nghẽn hoặc gây cản trở cho quá trình lọc", "Bơm bùn đã xử lý xong về bể lắng bùn", "Cả 3 đáp án đều đúng"]', 3, 'Hệ thống XLNT'),
('Có bao nhiêu bơm tuần hoàn bùn trong hệ thống', '["2", "4", "6", "8"]', 1, 'Hệ thống XLNT'),
('Có bao nhiêu bơm tuần hoàn bùn trong hệ thống nhận nhiệm vụ bơm bùn về bể bùn', '["2", "3", "4", "5"]', 0, 'Hệ thống XLNT'),
('Dòng định mức của bơm tuần hoàn bùn là bao nhiêu ?', '["2A", "1.5A", "1A", "0,9 A"]', 2, 'Hệ thống XLNT'),
('Có bao nhiêu bơm THB chạy với nhiệm vụ bơm tuần hoàn bùn qua các màng MBR', '["1", "2", "3", "4"]', 1, 'Hệ thống XLNT'),
('Các bơm tuần hoàn bùn được cài đặc chạy như thế nào ?', '["Chạy độc lập theo từng line", "Được cài đặc chạy 4 lần trong một giờ", "Chạy theo chế độ Man", "A và B đúng"]', 3, 'Hệ thống XLNT'),
('Các bơm tuần hoàn bùn có báo tín hiệu chạy hoặc sự cố về hệ thống Scada không ?', '["Có", "Không"]', 0, 'Hệ thống XLNT'),
('Các bơm tuần hoàn bùn được trang bị tính năng bảo vệ động cơ là gì?', '["Bảo vệ quá nhiệt qua Relay nhiệt", "Các tính năng bảo vệ sẵn có trên biến tần hiện hữu đang sử dụng cho bơm (Quá dòng,quá nhiệt...)", "A và B đúng", "A và B sai"]', 0, 'Hệ thống XLNT'),
('Số lượng bơm bể đầu vào?', '["1", "2", "3", "4"]', 1, 'Hệ thống XLNT'),
('Số lượng bơm bể điều hòa?', '["1", "2", "3", "4"]', 3, 'Hệ thống XLNT'),
('Cụm bơm hút màng gồm mấy bơm?', '["3", "4", "5", "6"]', 3, 'Hệ thống XLNT'),
('Số lượng máy khuấy chìm trên bể thiếu khí?', '["1", "2", "3", "4"]', 3, 'Hệ thống XLNT'),
('Số lượng máy thổi khí đang sử dụng trong dây chuyền?', '["1", "2", "3", "4"]', 2, 'Hệ thống XLNT'),
('Thiết bị đo pH online gồm mấy bộ?', '["1", "2", "3", "4"]', 1, 'Hệ thống XLNT'),
('Thiết bị đo DO online gồm mấy bộ?', '["1", "2", "3", "4"]', 1, 'Hệ thống XLNT'),
('Dòng định mức bơm bể đầu vào  là bao nhiêu?', '["5.1 (A)", "5.2 (A)", "5.3 (A)", "5.4 (A)"]', 3, 'Hệ thống XLNT'),
('Dòng định mức bơm bể điều hòa là bao nhiêu?', '["3.5 (A)", "3.6 (A)", "3.7 (A)", "3.8 (A)"]', 2, 'Hệ thống XLNT'),
('Dòng định mức bơm hút màng là bao nhiêu?', '["5.1 (A)", "5.2 (A)", "5.3 (A)", "5.4 (A)"]', 3, 'Hệ thống XLNT'),
('Dòng định mức bơm tuần hoàn bùn là bao nhiêu?', '["0.6 (A)", "0.7(A)", "0.8 (A)", "0.9 (A)"]', 3, 'Hệ thống XLNT'),
('Công suất thiết kế của hệ thống xử lý nước thải GĐ1 và GĐ2 là bao nhiêu ?', '["GĐ1: 360m³/ngày.đêm, GĐ2: 360m³/ngày.đêm", "GĐ1: 480m³/ngày.đêm, GĐ2: 360m³/ngày.đêm", "GĐ1: 360m³/ngày.đêm, GĐ2: 180m³/ngày.đêm", "GĐ1: 480m³/ngày.đêm, GĐ2: 180m³/ngày.đêm"]', 0, 'Hệ thống XLNT'),
('Quy chuẩn kỹ thuật quốc gia về nước thải sinh hoạt ký hiệu là gì?', '["QCVN 14:2008/BTNMT", "QCVN 15:2008/BTNMT", "QCVN 16:2008/BTNMT", "QCVN 17:2008/BTNMT"]', 0, 'Hệ thống RO'),
('QCVN 14:2008/BTNMT gồm mấy chỉ tiêu?', '["10", "11", "12", "13"]', 1, 'Hệ thống RO'),
('Nước thải sau xử lý của nhà ga hiện áp dụng theo cột nào của QCVN 14:2008/BTNMT?', '["Cột A", "Cột B", "Cột C", "Cột D"]', 1, 'Hệ thống RO'),
('Quy chuẩn kỹ thuật quốc gia đối với nước khoáng thiên nhiên và nước uống đóng chai là quy chuẩn gì?', '["QCVN 6-1:2010/BYT", "QCVN 7-1:2010/BYT", "QCVN 8-1:2010/BYT", "QCVN 9-1:2010/BYT"]', 0, 'Hệ thống RO'),
('Mức quy định Hàm lượng Clo dư trong nước uống theo Quy chuẩn QCVN 6-1:2010/BYT là bao nhiêu?', '["≤3 mg/l", "≤4 mg/l", "≤5mg/l", "≤6 mg/l"]', 2, 'Hệ thống RO'),
('Trạm XLNT có công suất thiết kế bao nhiêu?', '["450m3/ngày", "360m3/ngày", "280m3/ngày", "280m3/ngày"]', 1, 'Hệ thống XLNT'),
('Chỉ số DO là gì?', '["Lượng oxy hòa tan trong nước", "Lượng oxy trong không khí", "Lượng bùn hoạt tính", "Tổng hàm lượng rắn"]', 0, 'Hệ thống XLNT'),
('Hóa chất dùng để rửa màng MBR là gì?', '["HCl 10%", "Javel 10%", "NaOH", "NaHCO3"]', 1, 'Hệ thống XLNT'),
('Chỉ số TDS là gì?', '["Tổng hàm lượng bùn hoạt tính", "Tổng hàm lượng chất rắn hòa tan trong nước", "Lượng oxy hòa tan trong nước", "Tổng hàm lượng Sunphua"]', 1, 'Hệ thống XLNT'),
('Ứng dụng của máy khuấy chìm trong XLNT được thiết kế cho  những điều nào sau đây được sử dụng ?', '["Trộn nước thải và di chuyển bùn", "Hòa trộn và tuần hoàn của \nnước thải nước cống.", "Hòa trộn và tuần hoàn bùn.", "Cả 3 ý trên"]', 3, 'Hệ thống XLNT'),
('Cụm bơm Tuần hoàn nước bể màng MBR được chia làm mấy bơm?', '["1 cụm 1 bơm", "1 cụm 2 bơm", "1 cụm 3 bơm", "1 cụm 4 bơm"]', 1, 'Hệ thống XLNT'),
('Bơm tuần hoàn nước hoạt động theo tín hiệu nào', '["Tín hiệu phao", "Tín hiệu time", "Cả A và B."]', 1, 'Hệ thống XLNT'),
('Bơm tuần hoàn nước gồm có mấy bơm', '["2 Bơm", "3 bơm", "4 bơm"]', 2, 'Hệ thống XLNT'),
('Trong mỗi cụm bơm tuần hoàn nước bể màng MBR thì bơm hoạt động  như thế nào?', '["Hoạt động độc lập", "Hoạt động cùng lúc"]', 0, 'Hệ thống XLNT'),
('Dòng định mức bơm tuần hoàn nước .', '["2.3 ± 10%", "3.2 ± 10%", "5.2 ± 10%", "6.2 ± 10%"]', 0, 'Hệ thống XLNT'),
('Mỗi bể màng MBR có mấy bơm tuần bùn', '["1 bơm", "2 bơm", "3 bơm", "4 bơm"]', 0, 'Hệ thống XLNT'),
('Hệ bơm tuần hoàn bùn hoạt động như thế nào?', '["Hoạt động luôn phiên", "Hoạt động cùng lúc"]', 0, 'Hệ thống XLNT'),
('Bơm hóa chất số 1 dùng để bơm javel lên bể nào?', '["Bể màng MBR số 1 ,2", "Bể thiếu khí số 1,2"]', 0, 'Hệ thống XLNT'),
('Bơm bể điều hòa hoạt động phụ thuộc vào bể nào?', '["Bể đầu vào .", "Bể màng.", "Cả A và B."]', 1, 'Hệ thống XLNT'),
('Dòng định mức của máy khuấy chìm .', '["3.5 ± 10%", "2.7 ± 10%", "1.5 ± 10%", "4.2 ± 10%"]', 2, 'Hệ thống XLNT'),
('Dòng định mức của máy khuấy hóa chất.', '["1.6 ± 10%", "0.9 ± 10%", "2.2 ± 10%", "3,2 ± 10%"]', 1, 'Hệ thống XLNT'),
('Điện trở cuộn dây máy khuấy chìm', '["25.5 ± 5%", "3.2 ± 5%", "20.5 ± 5%", "15.6 ± 5%"]', 2, 'Hệ thống XLNT'),
('Hệ thống bơm không sử dụng biến tần của hệ thống XLNT có  mấy nhóm bơm?', '["4 Nhóm", "5 Nhóm", "7  Nhóm", "6 Nhóm"]', 2, 'Hệ thống XLNT'),
('Điện trở cuộn dây của bơm bể đầu vào', '["7.5 ± 5%", "6.5 ± 5%", "4.5 ± 5%", "2.5 ± 5%"]', 1, 'Hệ thống XLNT'),
('Công suất của bơm đầu vào số 1 và 2', '["2.5kw", "3.2kw", "5.5kw", "2.2kw"]', 3, 'Hệ thống XLNT'),
('Công suất của máy khuấy chìm 1,2,3,4', '["0.7 kw", "1.5kw", "2kw", "3.5kw"]', 0, 'Hệ thống XLNT'),
('Công suất của bơm tuần hoàn nước 1,2,3,4', '["2.2kw", "2.5kw", "1.5kw", "3kw"]', 2, 'Hệ thống XLNT'),
('Công suất của bơm tuần hoàn bùn 1,2,3,4', '["0.7kw", "1.5kw", "0.4kw", "2kw"]', 2, 'Hệ thống XLNT'),
('Trên mái nhà ga có tất cả bao nhiêu đèn báo không ?', '["26 Đèn", "27 Đèn", "28 Đèn", "29 Đèn"]', 1, 'Hệ thống chống sét và đèn báo không'),
('Vùng bảo vệ của kim thu sét trên mái nhà ga T2 bán kính (R) là bao nhiêu M Là an toàn?', '["50 mét", "60 mét", "70 mét", "80 mét"]', 1, 'Hệ thống chống sét và đèn báo không'),
('Nguồn cấp của đèn báo không được từ tủ nào đến ?', '["UBD-MRF-02-L/01\n UDB-RF-06-L/01", "NDB-RFT-02-L/01\nUDB-MEZ-06L/01", "NDB-RFT-02-L/01\nUDB-MEZ-07-L/01", "NDB-RFT-06-L/01\nUDB-MEZ-07-L/01"]', 1, 'Hệ thống chống sét và đèn báo không'),
('Tác dụng của đèn báo không dùng để làm gì?', '["Báo hiệu là vùng an toàn", "Báo hiệu có chướng ngại vật", "Báo hiệu khu vực sân bay"]', 1, 'Hệ thống chống sét và đèn báo không'),
('Nguồn cấp của đèn báo không là nguồn U hay nguồn thường?', '["Nguồn UPS", "Nguồn thường", "Cả 2 nguồn"]', 0, 'Hệ thống chống sét và đèn báo không'),
('Đội ĐNCT quản lý tất cả bao nhiêu cây kim thu sét ?', '["6", "7", "8", "9"]', 1, 'Hệ thống chống sét và đèn báo không'),
('Hiện tại nhà ga T2 đang dùng loại chống sét nào ?', '["Chống sét lan truyền", "Chống sét trực tiếp", "Cả A và B"]', 2, 'Hệ thống chống sét và đèn báo không'),
('Hệ thống chống sét trên mái nhà và tiếp địa làm việc có được kết nối chung với nhau không?', '["Kết nối chung", "Không kết nối chung", "Khi có sét đánh", "Khi không có sét đánh"]', 1, 'Hệ thống chống sét và đèn báo không'),
('Hệ thống chống sét lan truyền và tiếp địa làm việc kết nối chung với nhau thông qua thiết bị gì?', '["Thiết bị rơ le", "Thiết bị cắt lọc sét", "Thiết bị khởi động từ"]', 1, 'Hệ thống chống sét và đèn báo không'),
('Hệ thống chống sét lan truyền và tiếp địa làm việc có kết nối chung với nhau không?', '["Có", "Không"]', 1, 'Hệ thống chống sét và đèn báo không'),
('Ngưỡng cài đặt để sa thải 1 máy phát khi công suất hiện tại mỗi máy đạt bao nhiêu % ?', '["0.32", "0.28", "0.55", "0.6"]', 0, 'Hệ thống máy phát'),
('Nguồn động lực cấp cho 4 tủ bơm dầu của máy phát được lấy từ tủ nào đến?', '["NSB-UC-LP/01", "MSB-FPCP & ENGINE", "Từ LT1"]', 2, 'Hệ thống máy phát'),
('Nguồn động lực cấp cho động cơ bơm dầu máy phát được cấp nguồn 3 pha 4 dây hay 3 pha 3 dây ?', '["3 Pha 4 dây", "3 Pha 3 dây"]', 1, 'Hệ thống máy phát'),
('Lưu lượng bơm dầu máy phát 1 phút bơm được bao nhiêu L (L/p)?', '["70 L/p", "75 L/p", "80 L/p", "85 L/p"]', 1, 'Hệ thống máy phát'),
('Hệ thống bơm dầu máy phát hoạt động dựa trên tín hiệu gì?', '["Tín hiệu sensor báo mức High", "Tín hiệu sensor báo mức Low", "Tín hiệu điều khiển từ IBMS", "Tín hiệu từ máy phát"]', 1, 'Hệ thống máy phát'),
('Các bơm dầu máy phát được đấu sao hay tam giác ?', '["Đấu tam giác", "Đấu sao"]', 1, 'Hệ thống máy phát'),
('2 bơm dầu cấp cho 1 bồn dầu được hoạt đông theo thời gian nào?', '["Hoạt động xen kẻ nhau", "Khi mực dầu đến vạch LOW/LOW", "Chạy đồng thời cả 2 bơm"]', 1, 'Hệ thống máy phát'),
('Động cơ bơm dầu được bảo vệ quá nhiệt như thế nào?', '["Thông qua sensor nhiệt có sẵn trong bơm", "Thông rơlay nhiệt được lắp đặt tại tủ điều khiển"]', 1, 'Hệ thống máy phát'),
('Thời gian chạy luân phiên giữa các máy phát là bao nhiêu giờ ?', '["6 giờ", "5 giờ", "7 giờ", "4 giờ"]', 0, 'Hệ thống máy phát'),
('Bộ LOGO! 12/24RC trong tủ bơm dầu có đọc được các trạng thái mức dầu cao và mức dầu thấp không (High/High, Low/Low)?', '["Mức High/High", "Mức  Low/low", "Câu AB đều đúng", "Cả 3 đáp án đều sai"]', 2, 'Hệ thống máy phát'),
('Công suất bơm bể đầu vào?', '["200w", "2000w", "2200w", "2500w"]', 2, 'Hệ thống XLNT'),
('Thương hiệu bơm bể đầu vào hãng nào?', '["Pentax( ý)", "Ebara(Ý)", "Panasonic(Nhật)", "Shinmaywa( Nhật)"]', 3, 'Hệ thống XLNT'),
('Bơm bể đầu vào dùng kiểu khởi động gì?', '["DOL", "VFD", "Khởi động mềm", "Khởi động sao/tam giác"]', 0, 'Hệ thống XLNT'),
('Khi bơm đầu vào báo trip để bơm hoạt động lại việc tiên ra kiểm tra cần thao tác gì để bơm có thể chạy lại được?', '["Tắt áp bật khởi động lại", "Bật về chế độ Manu", "Tháo dây đảo pha", "Reset lại Rowle nhiệt"]', 3, 'Hệ thống XLNT'),
('Khi nào bơm bể đầu vào sẽ chạy?', '["Khi bể điều hòa cạn", "Khi bể đầu vào bị tràn", "Khi bể điều hòa cạn có tín hiệu gọi bơm và đảm bảo mực nước ở bể đầu vào", "A và B"]', 2, 'Hệ thống XLNT'),
('Lưu lượng của bơm bể đầu vào theo nhãn máy?', '["52 m3/h", "62 m3/h", "72 m3/h", "82m3/h"]', 2, 'Hệ thống XLNT'),
('Bơm bể đầu vào bơm nước vào bể nào trong hệ thống XLNT?', '["Bể sinh học thiếu khí", "Bể điều hòa", "Bể lọc màng MBR", "Bể nén bùn"]', 1, 'Hệ thống XLNT'),
('Trường hợp bơm chạy nhưng không lên nước, làm sao để biết được nhanh nhất?', '["Đo kẹp dòng bơm tại tủ điện", "Thông qua hệ thống giám sát trong phòng AOC hoặc phòng hòa", "Kiểm tra tại bể Điều hòa xem nước lên không", "Kiêmr tra lượng nước trong bể đầu vào"]', 2, 'Hệ thống XLNT'),
('Trong hệ thống bơm XLNT bơm nào có công suất lớn nhất?', '["Bơm Liftpit", "Bơm bể đầu vào", "Bơm bể điều hòa", "Bơm hút màng"]', 0, 'Hệ thống XLNT'),
('Bơm bể đầu vào gồm mấy con', '["2", "3", "4", "5"]', 0, 'Hệ thống XLNT'),
('Bơm bể đầu vào chạy như thế nào?', '["Chay luân phiên từng bơm một theo ngày", "Chay luân phiên từng bơm một theo ngày và chạy theo tín hiệu phao báo cao", "Chạy đồng thời 2 bơm theo tín hiệu phao báo cao", "Chạy theo cài đặt giờ sẵn"]', 1, 'Hệ thống XLNT'),
('"Quy định sử dụng điện an toàn trong nhà ga hành khách quốc tế Đà Nẵng" dán tại các quầy thuê bao gồm mấy điều?', '["8", "9", "10", "11"]', 1, 'An toàn điện nước quầy thuê'),
('"Nội quy sử dụng và sửa chữa điện" bao gồm mấy điều', '["8", "9", "10", "11"]', 2, 'An toàn điện nước quầy thuê'),
('"Quy định sử dụng điện an toàn trong nhà ga hành khách quốc tế Đà Nẵng" do ai ký?', '["Trưởng phòng kỹ thuật", "Tổng giám đốc", "Trưởng phòng nhân sự", "Đội trưởng đội ĐNCT"]', 1, 'An toàn điện nước quầy thuê'),
('"Nội quy sử dụng và sửa chữa điện" do ai ký?', '["Tổng giám đốc", "Đội trưởng đội ĐNCT", "Trưởng phòng kỹ thuật", "Trưởng phòng nhân sự"]', 2, 'An toàn điện nước quầy thuê'),
('Khi bảo trì, lắp đặt, sửa chữa điện phải làm gì để thông báo?', '["Treo bảng: \"Cấm đóng điện có người đang làm việc\" và không cần thông báo", "Không cần treo chỉ chụp hình thông báo lên zalo phòng kỹ thuật", "Treo bảng, chụp hình thông báo lên zalo phòng kỹ thuật", "Chụp hình gửi báo trưởng ca"]', 2, 'An toàn điện nước quầy thuê'),
('Khi vào kiểm tra điện tại các quầy thuê tác phong cần?', '["Vào kiểm tra không cần hỏi", "Chào hỏi nêu rõ lý do kiểm tra", "Kiểm tra, chỉ rõ những việc được và chưa được, giải thích rõ ràng, khoa học và lo gic", "B và C"]', 3, 'An toàn điện nước quầy thuê'),
('Theo Điều 2 trong quy định sử dụng ATĐ trong nhà ga hành khách quốc tế Đà Nẵng khi sửa chữa cần mấy người?', '["1", "2", "3", "4"]', 1, 'An toàn điện nước quầy thuê'),
('Tổng số lượng quầy thuê, văn phòng cần kiểm tra trong nhà ga là bao nhiêu?', '["83", "93", "103", "113"]', 2, 'An toàn điện nước quầy thuê'),
('Khi đi kiểm tra trong nhà ga các quầy xẩy để mất ATĐ nhưng không phối hợp bạn cần làm gì?', '["Không nói gì đi về", "Nói phân tích cho bên quầy thuê hiểu được những quy định về sử đụng điện của công ty và yêu cầu thực hiện nghiêm túc", "Gọi báo cho trưởng ca trình bầy sự việc nhờ giúp đỡ và ghi lại vào biên bản yêu cầu ký xác nhận", "B và C"]', 3, 'An toàn điện nước quầy thuê'),
('Đèn chiếu sáng tại Gate123 và Gae 8910 đang sử dụng loại đèn nào và công suất bao nhiêu?', '["FLD4-25w", "FDL5-21w", "FDL3-21W", "FDL2-13w"]', 2, 'Hệ thống chiếu sáng'),
('Đèn chiếu sáng tại các phòng WC sử dụng loại đèn và công suất bao nhiêu?', '["FDL1-8w", "FDL2-13w", "FDL4-25w", "ADL-25w"]', 0, 'Hệ thống chiếu sáng'),
('Đèn chiếu sáng khu vực mái kín ga đến sử dụng những loại đèn nào?', '["FLD8-FDL7-FL3", "FDL5-FDL4-FLD6", "ADL1-FDL4-ADL2", "ADL1-FDL4-FDL6"]', 3, 'Hệ thống chiếu sáng'),
('Đèn chiếu sáng khu vực ghế chờ trần thấp các Gate4,5,6,7 đang sử dụng loại đèn và công suất bao nhiêu?', '["ADL1-25w", "FDL2-13w", "ADL3-47w", "ADL2-35w"]', 1, 'Hệ thống chiếu sáng'),
('Đèn chiếu hải quan ga đến sử dụng loại đèn nào?', '["FDL7-FDL8", "FDL2-FDL3", "ADL2-ADL3", "FDL3-FDL4"]', 0, 'Hệ thống chiếu sáng'),
('Công suất bơm bể điều bao nhiêu?', '["1.5kw", "2.2kw", "2.5kw", "3kw"]', 0, 'Hệ thống XLNT'),
('Công suất máy thổi khí bao nhiêu?', '["5.5kw", "7kw", "7.5kw", "9kw"]', 2, 'Hệ thống XLNT'),
('Công suất bơm hút màn bao nhiêu?', '["2.2kw", "3kw", "5kư", "5.5kw"]', 0, 'Hệ thống XLNT'),
('Hệ thống XLNT xử dụng bao nhiêu bơm bể điều hoà?', '["1", "2", "3", "4"]', 3, 'Hệ thống XLNT'),
('Hệ thống XLNT xử dụng bao nhiêu bơm thổi khí?', '["1", "2", "3", "4"]', 3, 'Hệ thống XLNT'),
('Hệ thống XLNT xử dụng bao nhiêu bơm hút màng?', '["4", "5", "6", "7"]', 2, 'Hệ thống XLNT'),
('Động cơ fault, màn hình led biến tần ATV310 suất hiện mã lỗi F010 là lỗi gì?', '["Ngắn mạch động cơ", "Quá tốc độ", "Lỗi mất tín hiệu ngõ vào AI", "Quá dòng"]', 3, 'Hệ thống XLNT'),
('Động cơ fault, màn hình led biến tần ATV310 suất hiện mã lỗi F014 là lỗi gì?', '["Mất 1 pha ngõ vào", "Lỗi thấp áp", "Quá dòng", "Quá tốc độ"]', 0, 'Hệ thống XLNT'),
('Động cơ fault, màn hình led biến tần ATV310 suất hiện mã lỗi F015 là lỗi gì?', '["Mất 1 pha ngõ vào", "Lỗi thấp áp", "Quá dòng", "Mất 3 pha ngõ ra"]', 3, 'Hệ thống XLNT'),
('Động cơ fault, màn hình led biến tần ATV310 suất hiện mã lỗi F017 là lỗi gì?', '["Quá dòng", "Mất pha ngõ vào", "Mất 1 pha ngõ vào", "Mất 3 pha ngõ ra"]', 1, 'Hệ thống XLNT'),
('Biến tần ATV310 set tham số 301 chọn 00 có nghĩa là gì?', '["Set giá trị tần số động cơ 50hz", "Set giá trị tần số động cơ 60hz", "Set giá trị bảo vệ quá áp", "Set giá trị thấp áp"]', 0, 'Hệ thống XLNT'),
('Biến tần ATV310 set tham số 302 cài đặt 1.5 có nghĩa là gì?', '["Set dòng định mức động cơ 1.5A", "Set công suất định mức của động cơ 1.5kw", "Set thời gian tăng tốc động cơ 1.5s", "Set thời gian giảm tốc động cơ 1.5s"]', 1, 'Hệ thống XLNT'),
('Biến tần ATV310 set tham số 501 cài đặt 10 có nghĩa là gì?', '["Set dòng định mức động cơ 10A", "Set thời gian giảm tốc động cơ 10s", "Set thời gian tăng tốc động cơ 10s", "Set số vòng quay của động cơ"]', 2, 'Hệ thống XLNT'),
('Biến tần ATV310 set tham số 305 cài đặt 3.7 có nghĩa là gì?', '["Set thời gian giảm tốc động cơ", "Set dòng điện định mức động cơ", "Set kiểu điều khiển động cơ", "Set tần số hoạt động động cơ"]', 1, 'Hệ thống XLNT'),
('Các bước kiểm tra động cơ khi biến tần ATV310 xuất hiện mã lỗi F010 trên màn hình Led', '["Off nguồn, ON nguồn cho động cơ chạy", "Off nguồn, đảo pha động cơ, On nguồn cho động cơ chạy", "Off nguồn, chuyển swtich Off, kiểm tra cách điện, điện trở cuộn dây, On nguồn chuyển switch Auto đo dòng so sánh kết quả với các đợt KTĐK"]', 2, 'Hệ thống XLNT'),
('Hệ thống máy thổi khí của khu vực XLNT giai đoạn 2 bao gồm:', '["1 máy công suất lớn chạy cho toàn bộ hệ thống", "2 máy chạy luân phiên", "2 máy chạy song song", "3 máy chạy luân phiên 2 máy một lần"]', 0, 'Hệ thống XLNT'),
('Các trường hợp đưa máy biến áp ra khỏi vận hành.', '["- Khi hệ thống rơ le bảo vệ máy biến áp bị hư hỏng.\n - Có tiếng kêu lạ, rung động bất thường.", "Nhiệt độ cuộn dây tăng lên bất thường và liên tục trong điều kiện bình thường, phụ tải không quá định mức.", "Các sứ bị rạn, vỡ, bị phóng điện bề mặt. Đầu cose bị nóng, đỏ.", "Cả 3 đáp án đều đúng"]', 3, 'Hệ thống trung thế'),
('Khi máy biến áp bị quá tải hoặc bất thường, phải kiểm tra các hạng mục sau.', '["Kiểm tra dòng điện và điện áp các pha", "- Kiểm tra nhiệt độ cuộn dây \n - Kiểm tra tình trạng làm việc của các bộ làm mát", "- Kiểm tra tiếng kêu, tiếng động của biến áp\n - Kiểm tra tình trạng làm việc của hệ thống rơ le bảo vệ", "Cả 3 đáp án đều đúng"]', 3, 'Hệ thống trung thế'),
('Quy định đưa máy cắt ra vị trí thử nghiệm.', '["Xác nhận máy cắt đã ở trạng thái mở", "Xác nhận khóa lock thao tác ở vị trí nằm ngang", "- Dùng cần thao tác chuyên dụng tra vào lỗ thao tác và quay ngược chiều kim đồng hồ để đưa máy cắt ra vị trí Test\n - Kiểm tra và xác nhận máy cắt đã ở vị trí Test", "Cả 3 đáp án đều đúng"]', 3, 'Hệ thống trung thế'),
('Quy định đóng dao đất các lộ ra.', '["- Xác nhận máy cắt đã ở vị trí Test.\n- Xác nhận máy cắt ở trạng thái OFF", "- Đưa cần dao đất vào lỗ thao tác theo phương thẳng đứng", "- Xoay cần thao tác dao đất cùng chiều kim đồng hồ một góc khoảng 95 độ\n - Kiểm tra bộ chỉ thị dao đất đã đóng, và rút cần thao tác", "Cả 3 đáp án đều đúng"]', 3, 'Hệ thống trung thế'),
('Quy định mở dao đất các lộ ra.', '["Đưa cần thao tác dao đất vào lỗ thao tác theo phương ngang.", "Xoay cần thao tác ngược chiều kim đồng hồ một góc khoảng 95 độ", "Kiêm tra bộ chỉ thị dao đất ở vị trí mở, và rút cần thao tác.", "Cả 3 đáp án đều đúng"]', 3, 'Hệ thống trung thế'),
('Quy định vận hành dao đất thanh cái 412-14.', '["Đảm bảo toàn bộ máy cắt kết giàn với thanh cái C42 đều nằm ở vị trí “thí nghiệm”", "Rút chìa khoá “BB1” ở mỗi máy cắt cắm vào dãy EC1 khoang “TUC41” để giải lock và rút chìa “EC1” cắm vào khoang dao đất “412-24” để giải lock.", "Tiếp tục thực hiện đóng/mở như quy định đóng/mở dao đất các lộ ra.", "Cả 3 đáp án đều đúng"]', 3, 'Hệ thống trung thế'),
('Quy định vận hành dao đất thanh cái TUC41-14', '["Đảm bảo toàn bộ máy cắt kết giàn với thanh cái C41 đều nằm ở vị trí “thí nghiệm”", "Rút chìa khoá “BB1” ở mỗi máy cắt cắm vào khoang “TUC41” để rút chìa “EC2” cắm vào khoang dao đất “TUC41-14” để giải lock.", "Tiếp tục thực hiện đóng/mở như quy định đóng/mở dao đất các lộ ra.", "Cả 3 đáp án đều đúng"]', 3, 'Hệ thống trung thế'),
('Quy định vận hành dao đất 471-76', '["Đảm bảo máy cắt 471 nằm ở vị trí “thí nghiệm”.", "- Xác nhận với Điện lực Thanh Khê rằng đã cắt máy cắt đầu tuyến 471HKQT và cô lập mạch điều khiển AC/DC\n - Xác nhận với Điện lực Thanh Khê đã mở dao cách ly và tiếp địa di động ở đầu tuyến.", "Tiếp tục thực hiện đóng/mở như quy định đóng/mở dao đất các lộ ra.", "Cả 3 đáp án đều đúng"]', 3, 'Hệ thống trung thế'),
('Mạch liên động 471 đóng được khi', '["412 mở", "471-76 mở", "TUC41-14 mở.", "Cả 3 đáp án đều đúng"]', 3, 'Hệ thống trung thế'),
('471-76 thao tác được khi', '["471 ở vị trí Test", "Ngăn lộ 471 mất điện", "A, B đều đúng", "A, B đều sai"]', 2, 'Hệ thống trung thế'),
('Dao tiếp địa TUC41-14 thao tác được khi', '["Tất cả các máy cắt trên thanh cái C41 ở vị trí Test", "Thanh cái C41 mất điện.", "A, B đều đúng", "A, B đều sai"]', 2, 'Hệ thống trung thế'),
('Máy cắt Outgoing đóng được Khi', '["Các dao đất tương ứng ở vị trí mở", "TUC41-14 mở", "A, B đều đúng", "A, B đều sai"]', 2, 'Hệ thống trung thế'),
('Dao đất Outgoing thao tác được khi', '["Máy cắt Outgoing ở vị trí Test", "Ngăn lộ tương ứng mất điện.", "A, B đều đúng", "A, B đều sai"]', 2, 'Hệ thống trung thế'),
('Máy cắt Incoming đóng được khi', '["Dao đất tương ứng ở vị trí mở", "TUC42-14 mở", "A, B đều đúng", "A, B đều sai"]', 2, 'Hệ thống trung thế'),
('Dao đất Incoming thao tác được khi', '["Máy cắt Incoming ở vị trí Test", "Ngăn lộ tương ứng mất điện.", "A, B đều đúng", "A, B đều sai"]', 2, 'Hệ thống trung thế'),
('Trên rơ le micom, đèn "Trip Led" màu đỏ sáng khi', '["Báo hiệu các chức năng bảo vệ của rơ le đã làm việc, hệ thống bị sự cố và rơ le đã gửi lệnh cắt máy cắt.", "Báo hiệu các chức năng cảnh báo của rơ le đã làm việc, hệ thống vẫn đang làm việc và máy cắt vẫn đang trạng thái làm việc bình thường.", "Hệ thống hoạt động bình thường.", "Tất cả đều đúng"]', 0, 'Hệ thống trung thế'),
('Trên rơ le micom, đèn " Alarm Led" màu vàng sáng khi', '["Báo hiệu các chức năng cảnh báo của rơ le đã làm việc, hệ thống vẫn đang làm việc và máy cắt vẫn đang trạng thái làm việc bình thường.", "Hệ thống hoạt động bình thường.", "Báo hiệu rơ le bị lỗi phần cứng, cần thay thế.", "Tất cả đều đúng"]', 0, 'Hệ thống trung thế'),
('Trên rơ le micom, đèn " Warning Led" màu cam sáng khi', '["Báo hiệu rơ le bị lỗi phần cứng, cần thay thế.", "Hệ thống hoạt động bình thường.", "A, B đều đúng", "Tất cả đều đúng"]', 0, 'Hệ thống trung thế'),
('Trên rơ le micom, đèn "Healthy Led" màu xanh sáng khi', '["Báo hiệu rơ le bị lỗi phần cứng, cần thay thế.", "Báo hiệu các chức năng bảo vệ của rơ le đã làm việc, hệ thống bị sự cố và rơ le đã gửi lệnh cắt máy cắt.", "Báo hiệu các chức năng cảnh báo của rơ le đã làm việc, hệ thống vẫn đang làm việc và máy cắt vẫn đang trạng thái làm việc bình thường.", "Hệ thống hoạt động bình thường."]', 2, 'Hệ thống trung thế'),
('Thiết định quá dòng khởi động bảo vệ cấp 1 ở máy cắt 471', '["I= 0.85 In, t= 0.025s", "I= 3 In, t= 0s", "Ie= 0.125 Ien, t= 0.03s", "Tất cả đều sai"]', 0, 'Hệ thống trung thế'),
('Thiết định quá dòng khởi động bảo vệ cấp 2 ở máy cắt 471', '["I= 0.85 In, t= 0.025s", "I= 3 In, t= 0s", "Ie= 3 Ien, t= 0.03s", "Tất cả đều sai"]', 1, 'Hệ thống trung thế'),
('Thiết định quá dòng chạm đất bảo vệ cấp 1 ở máy cắt 471', '["Ie= 0.125 Ien, t= 0.03s", "I= 0.85 In, t= 0.025s", "Ie= 3 Ien, t= 0.03s", "I= 3 In, t= 0s"]', 0, 'Hệ thống trung thế'),
('Hiện tại tất cả MBA của nhà ga đang sử dụng nấc phân áp bao nhiêu ?', '["23,1 kV", "22kV", "22,55kV", "23,05kV"]', 0, 'Hệ thống trung thế'),
('Phòng LT1 cấp nguồn cho những LC nào ?', '["1, 3, 5, 7", "2, 4, 6", "1, 2, 3, 4", "1, 2, 3"]', 2, 'Hệ thống hạ thế'),
('Phòng LT2 cấp nguồn cho những LC nào ?', '["1, 3, 5, 7", "2, 4, 6", "5, 6, 7", "1, 2, 3"]', 2, 'Hệ thống hạ thế'),
('Nhà ga có bao nhiêu máy biến áp ?', '["5", "7", "9", "11"]', 3, 'Hệ thống hạ thế'),
('Nhà ga có bao nhiêu máy hạ áp ?', '["5", "7", "9", "11"]', 1, 'Hệ thống hạ thế'),
('Hiện tại nhánh phụ tải nào của nhà ga đang sử dụng 2 bộ PCSn 60A ?', '["UC-01", "PTB-01", "PTB-03", "PTB-02"]', 3, 'Hệ thống hạ thế'),
('Công suất máy biến áp cho các nhánh PTB 1,2,3,4 là bao nhiêu kVA?', '["1500", "1800", "2000", "2200"]', 0, 'Hệ thống hạ thế'),
('Người vận hành giao tiếp với ATS thông qua bộ phận nào ?', '["Màn hình HMI", "BA", "IVE", "Remote"]', 1, 'Hệ thống hạ thế'),
('Công suất máy biến áp cho các nhánh UC1,2,3 là bao nhiêu kVA?', '["1500", "1800", "2000", "2200"]', 2, 'Hệ thống hạ thế'),
('Busway kết nối từ máy biến áp 1500kVA đến các nhánh PTB1,2,3,4 có dòng định mức là bao nhiêu Ampe ?', '["2000", "2500", "3000", "3200"]', 1, 'Hệ thống hạ thế'),
('Tủ tụ bù trong các phòng LT có tác dụng gì?', '["Ổn định điện áp", "Ổn định tần số", "Bù công suất phản kháng", "Bù công suất biểu kiến"]', 2, 'Hệ thống hạ thế'),
('Busway kết nối từ máy biến áp 2000kVA đến các nhánh UC1,2,3 có dòng định mức là bao nhiêu Ampe ?', '["2000", "2500", "3000", "3200"]', 3, 'Hệ thống hạ thế'),
('Máy cắt tổng của các nhánh NMB là loại gì ?', '["MCB", "MCCB", "ACB", "RCBO"]', 2, 'Hệ thống hạ thế'),
('Máy cắt tổng của các nhánh PTB có dòng định mức bao nhiêu Ampe ?', '["2000", "2500", "3000", "3200"]', 1, 'Hệ thống hạ thế'),
('Máy cắt tổng của các nhánh UC có dòng định mức bao nhiêu Ampe ?', '["2000", "2500", "3000", "3200"]', 3, 'Hệ thống hạ thế'),
('Muốn đóng ACB coupler tại phòng LT1 (trong trường hợp nguồn cấp cho PTB1 sự cố) thì cần thực hiện các bước gì ?', '["1. Off ACB tổng nhánh PTB1.\n2. On ACB coupler.", "1. Off toàn bộ phụ tải nhánh PTB1.\n2. Off ACB tổng PTB1, rút chìa khóa interlook.\n3. Gắn chìa khóa interlook vào ACB coupler, On ACB coupler.\n4. On lần lượt các phụ tải nhánh PTB1.", "1. Off toàn bộ phụ tải nhánh PTB2.\n2. Off ACB tổng PTB1, rút chìa khóa interlook.\n3. Gắn chìa khóa interlook vào ACB coupler, On ACB coupler.\n4. On lần lượt các phụ tải nhánh PTB1.", "1. Off toàn bộ phụ tải nhánh PTB1.\n2. Off ACB tổng PTB2, rút chìa khóa interlook.\n3. Gắn chìa khóa interlook vào ACB coupler, On ACB coupler.\n4. On lần lượt các phụ tải nhánh PTB1."]', 1, 'Hệ thống hạ thế'),
('Nguồn chính của UPS-LTG lấy từ PTB  nào ?', '["1", "2", "3", "4"]', 0, 'Hệ thống hạ thế'),
('Nguồn chính của UPS-EQPT lấy từ PTB  nào ?', '["1", "2", "3", "4"]', 3, 'Hệ thống hạ thế'),
('THD (Total harmonic distortion) nghĩa là gì ?', '["Tổng độ méo hài", "Tổng công suất phản kháng", "Tổng dòng rò hệ thống"]', 0, 'Hệ thống hạ thế'),
('Chức năng của Role REA 200e là gì?', '["Bảo vệ quá dòng", "Bảo vệ chạm đất", "Bảo vệ quá dòng và chạm đất", "Bảo vệ quá dòng hoặc chạm đất"]', 2, 'Hệ thống hạ thế'),
('Máy cắt ACB tại các phòng LC có bao nhiêu vị trí làm việc ?', '["1", "2", "3", "4"]', 2, 'Hệ thống hạ thế'),
('Hệ số Cos phi đang set tại các tủ tụ bù là bao nhiêu ?', '["0.8", "0.9", "0.95", "1"]', 2, 'Hệ thống hạ thế'),
('Tỉ số TI tại các PTB là bao nhiêu ?', '["1500/5", "2500/5", "3200/5", "3500/5"]', 1, 'Hệ thống hạ thế'),
('Tỉ số TI tại các nhánh UC là bao nhiêu ?', '["1500/5", "2500/5", "3200/5", "3500/5"]', 2, 'Hệ thống hạ thế'),
('Giá trị cài đặt O/C trên Relay REA200e tại các PTB là bao nhiêu ?', '["100%/1s", "100%/2s", "90%/1s", "200%/2s"]', 0, 'Hệ thống hạ thế'),
('Giá trị cài đặt E/F trên Relay REA200e tại các PTB là bao nhiêu ?', '["10.5%/1s", "100%/1s", "90%/1s", "200%/2s"]', 0, 'Hệ thống hạ thế'),
('Hãy cho biết hệ thống lọc sóng hài (AHF) được đấu vào mạng điện theo kiểu gì tại nhà ga T2?', '["Đấu nối tiếp vào mạng điện trung thế 22kV", "Đấu song song vào mạng điện trung thế 22kV", "Đấu nối song song vào mạng điện hạ thế ~400V", "Đấu nối tiếp vào mạng điện hạ thế ~400V"]', 2, 'Hệ thống hạ thế'),
('Tại tủ OG, nếu trời chuyển tối trước thời gian cài đặt của Timer (17:30) thì ?', '["KTV chuyển sang chế độ Man để ON tủ điện", "Photo sensor sẽ tác động", "Chờ đến lúc Timer On"]', 2, 'Hệ thống chiếu sáng'),
('Chiếu sáng quanh nhà UC lấy nguồn từ đâu ?', '["Bot bảo vệ UC", "Tủ OG1", "Phòng LT1", "Tủ điện LP trong nhà UC"]', 1, 'Hệ thống chiếu sáng'),
('Tủ điện OG2 có bao nhiêu nhánh QM ?', '["2", "3", "4", "5"]', 2, 'Hệ thống chiếu sáng'),
('Tủ điện OG2 có bao nhiêu nhánh QM được đóng ngắt thông qua Contactor?', '["2", "3", "4", "5"]', 1, 'Hệ thống chiếu sáng'),
('Chiếu sáng đường tầng tại tủ OG2 được cấp nguồn từ các QM nào?', '["1,2", "1,3", "2,4", "3,4"]', 0, 'Hệ thống chiếu sáng'),
('Các MCCB tổng tủ NSB trong các LC có dòng tải định mức bao nhiêu (A) ?', '["100(A)", "160(A)", "200(A)", "250(A)"]', 3, 'Hệ thống hạ thế'),
('Ký hiệu UI trên MCCB có ý nghĩa gì?', '["Điện áp cách điện cực tiểu", "Điện áp cách điện trung bình", "Điện áp cách điện cực đại mà MCCB có thể chịu đựng", "Cả 3 đáp án trên đều sai."]', 2, 'Hệ thống hạ thế'),
('Ký hiệu Ue trên MCCB có ý nghĩa gì?', '["Điện áp làm việc định mức của MCCB", "Dòng tải làm việc định mức của MCCB", "Cả hai đáp án A, B đều đúng", "Cả hai đáp án A, B đều sai"]', 0, 'Hệ thống hạ thế'),
('Ký hiệu Icu trên MCCB có ý nghĩa gì?', '["Khả năng ngắt mạch tại dòng điện ngắn mạch trung bình của MCCB trong điều kiện thường(kA).", "Khả năng ngắt mạch tại dòng điện ngắn mach cực đại của MCCB trong điều kiện thường(kA).", "Khả năngngắt mạch tại dòng điện ngắn mạch của MCCB trong điều kiện Khắc nghiệt(kA).", "Cả A, B, C đều sai"]', 1, 'Hệ thống hạ thế'),
('Ký hiệu UImp trên MCCB có ý nghĩa gì?', '["Dòng điện cực đại mà MCCB có thể chịu đựng.", "Công suất cực đại mà MCCB có thể chịu đựng.", "Điện áp cực đại (điện áp xung định mức)mà MCCB có thể chịu đựng", "Cả A, B, C đều đúng"]', 2, 'Hệ thống hạ thế'),
('Ký hiệu Ir trên MCCB có ý nghĩa gì?', '["Dòng điều chỉnh để bảo vệ quá tải, nhỏ hơn hoặc bằng In", "Dòng định mức", "dòng bảo vệ ngắn mạch", "Cả A, B, C đều sai"]', 0, 'Hệ thống hạ thế'),
('Ký hiệu Im trên MCCB có ý nghĩa gì?', '["Dòng cắt định mức", "Dòng bảo vệ ngắn mạch", "Dòng bảo vệ chạm đất", "Cả A, B, C đều sai"]', 1, 'Hệ thống hạ thế'),
('Ký hiệu Cat A trên MCCB có ý nghĩa gì?', '["Không có thời gian trễ ngắn hạn định trước trong trường hợp ngắn mạch", "Có thời gian trễ ngắn hạn định trước trong trường hợp ngắn mạch", "Có thời gian trễ ngắn hạn định trước trong trường hợp quá tải", "Cả A, B, C đều sai"]', 0, 'Hệ thống hạ thế'),
('Bộ re lay bảo vệ chạm đất(ELR) tại các tủ NSB đang cài đặt thông số bảo vệ  bao nhiêu?', '["I: 5(A)\nT: 5(S)", "I: 3(A)\nT: 5(S)", "I: 5(A)\nT: 7(S)", "I: 5(A)\nT: 3(S)"]', 3, 'Hệ thống hạ thế'),
('Cầu chì tại các tủ NDB có dòng định mức là bao nhiêu?', '["1A", "2A", "3A", "4A"]', 1, 'Hệ thống hạ thế'),
('Hiện tại đài phun nước trung tâm đang xử dụng mấy bơm?', '["1", "2", "3", "4"]', 1, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Bơm đài phun nước trung tâm có dùng biến tần không?', '["Không", "Có"]', 1, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Vì sao phải sử dụng biến tần cho bơm đài phun nước trung tâm?', '["Khởi động bơm một cách từ từ và giữ tần số bơm ổn định để đạt chiều cao cột nước như mong muốn", "Khởi động bơm một cách nhanh chóng và giữ tần số bơm ổn định để đạt chiều cao cột nước như mong muốn", "Khởi động bơm từ từ dẫn đến tiết kiệm điện năng tiêu thụ.", "Khởi động Bơm êm ái bảo vệ bơm tránh mài mòn cơ khí."]', 0, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Các bơm đài phun nước trung tâm hoạt động luân phiên hay đồng thời?', '["Luân phiên", "Đồng thời", "Vừa luân phiên, vừa đồng thời"]', 0, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Các bơm bể tam giác có sử dụng biến tần không?', '["Có", "Không"]', 1, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Vì sao các bơm bể tam giác không cần sử dụng biến tần?', '["Không cần điều chỉnh tần số", "Công suất bơm nhỏ", "Cần bơm hoạt động hết công suất", "Cả A, B và C đều Đúng"]', 3, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Thiết bị nào điều khiển sự hoạt động của bơm hố Liftpit?', '["Timer thời gian", "Biến tần", "Phao mức cạn và phao mức đầy", "Cả 3 đáp án trên"]', 2, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Bơm hố Liftpit hoạt động đồng thời hay luân phiên', '["Luân phiên", "Đồng thời"]', 0, 'Hệ bơm tiểu cảnh và bơm Liftpit'),
('Khi mực nước tại hố Liftpit đầy thì có cảnh báo về màn hình Scada không?', '["không", "Có"]', 1, 'Hệ bơm tiểu cảnh và bơm Liftpit');